fix: the issue with converting non-finite values to JSON string
awslabs/clickstream-swift pull request #66
Opened 2024-05-30 02:26 UTC by zhu-xiaowei

## Description
1. fix the issue with converting non-finite values to JSON string

## General Checklist

- [x] Added new tests to cover change, if needed
- [x] Build succeeds using Swift Package Manager
- [x] All unit tests pass
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [ ] Documentation update for the change if required
- [x] PR title conforms to conventional commit style
- [ ] If breaking change, documentation/changelog update with migration instructions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-02 05:16 UTC, zxkane requested changes

2024-06-02 05:16 UTC, zxkane commented on Sources/Clickstream/Dependency/Clickstream/Event/Event.swift
> +        static let ATTRIBUTE_VALUE_NOT_FINITE = 2_005
change to infinite

2024-06-02 05:16 UTC, zxkane commented on Sources/Clickstream/Dependency/Clickstream/Event/EventChecker.swift
> +            let errorString = "the value for attribute name: \(key) is not finite"
use infinite

2024-06-02 14:13 UTC, zhu-xiaowei commented on Sources/Clickstream/Dependency/Clickstream/Event/Event.swift
> +        static let ATTRIBUTE_VALUE_NOT_FINITE = 2_005
fixed

2024-06-02 14:13 UTC, zhu-xiaowei commented on Sources/Clickstream/Dependency/Clickstream/Event/EventChecker.swift
> +            let errorString = "the value for attribute name: \(key) is not finite"
done.

2024-06-03 01:51 UTC, zxkane approved these changes

2024-06-03 01:51 UTC, merged